In [5]:
import numpy as np
timesteps = 100
input_features = 32
output_features = 64
inputs = np.random.random((timesteps, input_features))
state_t = np.zeros((output_features,))
W = np.random.random((output_features, input_features))
print('wagi:\n',W)
U = np.random.random((output_features, output_features))
print('\n', U)
b = np.random.random((output_features,))
print('przesunięcie:\n',b)
successive_outputs = []
for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) + np.dot(U, state_t) + b)
    successive_outputs.append(output_t)
    # print("obliczenie:", output_t)
    state_t = output_t
    
final_output_sequence = np.concatenate(successive_outputs, axis=0)


print('wynik ostateczny: \n', final_output_sequence)

wagi:
 [[0.1242616  0.06108094 0.82305258 ... 0.81304407 0.52906221 0.94735242]
 [0.79663703 0.68105955 0.72152513 ... 0.11459588 0.31652851 0.31531822]
 [0.48802764 0.0353178  0.05669729 ... 0.55320729 0.3312356  0.59643631]
 ...
 [0.83195215 0.07539199 0.51224625 ... 0.14585566 0.83724441 0.43232236]
 [0.67233636 0.0101784  0.23298443 ... 0.44980552 0.71614211 0.11224585]
 [0.8978267  0.09716161 0.31084336 ... 0.27595622 0.69471369 0.4660982 ]]

 [[0.26835117 0.61202876 0.42222776 ... 0.16823545 0.55372029 0.18680752]
 [0.28200267 0.34647253 0.226535   ... 0.26429186 0.68418478 0.11934257]
 [0.36437586 0.07254558 0.00812218 ... 0.61559512 0.3479884  0.00514761]
 ...
 [0.46921779 0.07914125 0.44478698 ... 0.68565508 0.17161691 0.7344782 ]
 [0.72647022 0.43284857 0.86480425 ... 0.64619145 0.59368621 0.89658059]
 [0.717654   0.74041079 0.61204995 ... 0.94036928 0.14097688 0.64653748]]
przesunięcie:
 [8.88804948e-01 4.49042245e-01 5.38065174e-01 8.21726447e-01
 7.82723977e-01 6.31523805e